"""
Run this once to initialize the database:

    python seed.py

It will:
  1. Create all tables (safe to re-run; uses create_all, won't drop data)
  2. Create the Super Admin account from .env (SUPERADMIN_EMAIL / SUPERADMIN_PASSWORD)
  3. Create a demo shop "Sharma Auto Spares" with an owner, an employee,
     a handful of parts across vehicle types, a supplier, and a couple of
     sample invoices - so you can log in and see a populated ERP immediately.
"""
from datetime import date, timedelta
from decimal import Decimal
import os

# --- Ensure a backup encryption key exists BEFORE importing the app --------
# config.py calls load_dotenv() the moment it's imported (which happens as
# soon as `from app import create_app` runs below), so the key must already
# be on disk in .env before that import, not just in os.environ.
_basedir = os.path.dirname(os.path.abspath(__file__))
_env_path = os.path.join(_basedir, ".env")
_env_text = ""
if os.path.exists(_env_path):
    with open(_env_path, "r") as _f:
        _env_text = _f.read()

_has_key = any(
    line.startswith("BACKUP_ENCRYPTION_KEY=") and line.strip() != "BACKUP_ENCRYPTION_KEY="
    for line in _env_text.splitlines()
)
if not _has_key:
    from cryptography.fernet import Fernet
    _new_key = Fernet.generate_key().decode()
    with open(_env_path, "a") as _f:
        _f.write(f"\n# Auto-generated by seed.py — required to decrypt backups. Keep this safe!\n")
        _f.write(f"BACKUP_ENCRYPTION_KEY={_new_key}\n")
    print(f"[OK] Generated BACKUP_ENCRYPTION_KEY and saved it to .env")

if "BACKUP_TRIGGER_SECRET=" not in _env_text:
    import secrets as _secrets
    _new_secret = _secrets.token_hex(24)
    with open(_env_path, "a") as _f:
        _f.write(f"BACKUP_TRIGGER_SECRET={_new_secret}\n")
    print(f"[OK] Generated BACKUP_TRIGGER_SECRET and saved it to .env (for external cron use)")

_has_vapid = any(
    line.startswith("VAPID_PRIVATE_KEY=") and line.strip() != "VAPID_PRIVATE_KEY="
    for line in _env_text.splitlines()
)
if not _has_vapid:
    import base64
    from cryptography.hazmat.primitives.asymmetric import ec
    from cryptography.hazmat.primitives import serialization

    _vapid_key = ec.generate_private_key(ec.SECP256R1())
    # py_vapid (used inside pywebpush) expects base64url-encoded DER - NOT PEM.
    _der_bytes = _vapid_key.private_bytes(
        encoding=serialization.Encoding.DER,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    )
    _private_str = base64.urlsafe_b64encode(_der_bytes).rstrip(b"=").decode()

    _public_bytes = _vapid_key.public_key().public_bytes(
        encoding=serialization.Encoding.X962,
        format=serialization.PublicFormat.UncompressedPoint,
    )
    _public_b64 = base64.urlsafe_b64encode(_public_bytes).rstrip(b"=").decode()

    with open(_env_path, "a") as _f:
        _f.write(f"\n# Auto-generated by seed.py — Web Push (VAPID) keys for browser push notifications\n")
        _f.write(f"VAPID_PRIVATE_KEY={_private_str}\n")
        _f.write(f"VAPID_PUBLIC_KEY={_public_b64}\n")
    print(f"[OK] Generated VAPID push-notification keys and saved them to .env")

# --- IMPORTANT: ephemeral hosting filesystems (Render, Railway, etc.) ------
# The generated values above are written to a LOCAL .env file. On a platform
# whose filesystem resets on every deploy, this file (and everything just
# generated into it) disappears on the next deploy and gets silently
# regenerated with NEW random values — which would make old backups
# undecryptable and break any saved push subscriptions.
#
# If you're running this on Render/Railway/etc., after this first run, open
# the container's live .env (Render: Shell tab → `cat .env`) and copy
# BACKUP_ENCRYPTION_KEY, BACKUP_TRIGGER_SECRET, VAPID_PRIVATE_KEY, and
# VAPID_PUBLIC_KEY into your platform's permanent Environment Variables
# dashboard, so they stay fixed across every future deploy.

from app import create_app
from app.extensions import db
from app.models import (
    User, Role, Shop, ShopStatus, Subscription, Supplier, Part,
    Customer, LabourCharge, Godown, HelpArticle
)
from app.utils.stock import apply_stock_change, get_default_godown
from app.utils.helpers import generate_invoice_number
from app.models import Invoice, InvoiceItem, PaymentMethod, PaymentStatus

app = create_app()


def seed_help_articles():
    if HelpArticle.query.first():
        print("[SKIP] Help Center articles already exist.")
        return

    articles = [
        dict(category="beginner", order_index=1, title="Welcome to PartFlow ERP",
             slug="welcome-to-partflow-erp", body_html="""
<p>PartFlow ERP helps you manage spare parts, sales, purchases, and billing for your shop.</p>
<p><strong>Three types of logins:</strong></p>
<ul>
<li><strong>Super Admin</strong> — PartFlow's own team, manages all shops on the platform.</li>
<li><strong>Shop Owner</strong> — you. Full control of your shop's inventory, sales, employees, and reports.</li>
<li><strong>Employee</strong> — your staff. Can create sales and request purchases, but cannot delete
invoices, edit old transactions, or manually change stock — keeping your records safe.</li>
</ul>
<p>Use the left sidebar to move between sections. On mobile, tap the "Menu" button at the top to open it.</p>
"""),
        dict(category="beginner", order_index=2, title="Your First Day: Setup Checklist",
             slug="first-day-setup-checklist", body_html="""
<ol>
<li>Add your <strong>Suppliers</strong> (Inventory → Suppliers).</li>
<li>Add your <strong>Parts</strong> with opening stock and minimum stock level (Inventory → Parts → Add Part).</li>
<li>Add your <strong>Employees</strong> so they can log in and start billing (Team → Employees).</li>
<li>Set up <strong>Labour Charges</strong> you commonly bill (fitting, service, repair) so sales are faster.</li>
<li>If you have more than one warehouse, add a second <strong>Godown</strong> and use Stock Transfer to move
stock between them.</li>
</ol>
<p>Once this is done, you're ready to start billing customers from "New Sale".</p>
"""),
        dict(category="owner_guide", order_index=1, title="Managing Inventory & Stock Alerts",
             slug="managing-inventory-stock-alerts", body_html="""
<p>Every part has a <strong>Minimum Stock Level</strong>. When stock falls to or below this number, PartFlow
raises exactly one alert (it won't spam you every time you sell one more unit). The alert clears
automatically the moment you receive enough purchase stock to go back above the minimum.</p>
<p>Stock only ever changes through: a Sale, a Purchase Receipt, a Stock Transfer between godowns, or a manual
Stock Audit adjustment (Inventory → part → Stock History → Adjust Stock) — every one of these is logged
permanently so you can always see exactly what happened and who did it.</p>
"""),
        dict(category="owner_guide", order_index=2, title="Purchase Requests vs. Receiving Purchases",
             slug="purchase-requests-vs-receiving", body_html="""
<p>Employees can raise a <strong>Purchase Request</strong> when stock is running low. You approve or reject
it from Purchase Requests. <strong>Approving a request does not add any stock</strong> — it's just permission.
Stock only increases when you actually <strong>Receive</strong> the purchase (Inventory → Receive Purchase),
where you record the real invoice number, quantity, price and GST from your supplier's bill.</p>
"""),
        dict(category="owner_guide", order_index=3, title="Understanding GST Invoices",
             slug="understanding-gst-invoices", body_html="""
<p>Every sale generates a numbered GST invoice automatically. You can download it as a PDF, or share a
summary directly on WhatsApp with one tap (no extra app or fees needed). Partial and credit payments are
tracked per-invoice, and the Customer page shows a full ledger of what's still due.</p>
"""),
        dict(category="owner_guide", order_index=4, title="Backups & Restoring Your Data",
             slug="backups-and-restoring", body_html="""
<p>Your shop's data is backed up automatically every day, every week, and every month — encrypted, and
completely separate from every other shop on the platform. If you ever need to undo a serious mistake,
contact PartFlow Support; only a Super Admin can restore a backup, and restoring your shop never touches
any other shop's data.</p>
"""),
        dict(category="employee_guide", order_index=1, title="Making a Sale",
             slug="making-a-sale-employee", body_html="""
<p>Go to <strong>New Sale</strong>. Enter the customer's name and mobile number (if they've bought from you
before, their details will be reused automatically), add the parts they're buying, add any labour/service
charges, choose the payment method, and submit. The invoice, GST, and stock deduction all happen
automatically.</p>
<p>You cannot delete invoices, edit old sales, or manually change stock counts — if something's wrong,
ask your shop owner.</p>
"""),
        dict(category="employee_guide", order_index=2, title="Requesting a Purchase",
             slug="requesting-a-purchase-employee", body_html="""
<p>If a part is running low, go to <strong>Purchase Requests</strong>, pick the part and quantity, and
submit. Your shop owner will approve or reject it. You'll see the status update on the same page.</p>
"""),
        dict(category="faq", order_index=1, title="Why didn't I get a low-stock alert for every sale?",
             slug="faq-why-no-repeat-alerts", body_html="""
<p>By design. PartFlow sends exactly one alert when a part first drops to or below its minimum stock level,
so you're not flooded with repeat alerts on every subsequent sale of the same low-stock part. The alert
clears automatically once you restock above the minimum.</p>
"""),
        dict(category="faq", order_index=2, title="Can I use this on my phone?",
             slug="faq-mobile-use", body_html="""
<p>Yes — PartFlow ERP is fully responsive and works in any mobile browser (Chrome, Safari, etc.). No app
install is required.</p>
"""),
        dict(category="faq", order_index=3, title="What happens if my subscription expires?",
             slug="faq-subscription-expiry", body_html="""
<p>You'll get a reminder notification a few days before expiry. If it lapses, your shop's owner and employee
logins are paused until a Super Admin renews the subscription — your data is not deleted.</p>
"""),
        dict(category="whats_new", order_index=1, title="Multi-Godown Stock Transfer",
             slug="whats-new-godown-transfer", body_html="""
<p>You can now add multiple godowns (warehouses/branches) and transfer stock between them, with full
audit history. See Inventory → Godowns.</p>
"""),
        dict(category="whats_new", order_index=2, title="Free WhatsApp Sharing for Invoices",
             slug="whats-new-whatsapp-sharing", body_html="""
<p>Invoices and customer statements now have a "Share on WhatsApp" button — no API fees, no setup, just
tap and send.</p>
"""),
    ]

    for a in articles:
        db.session.add(HelpArticle(**a, is_published=True))
    db.session.commit()
    print(f"[OK] Seeded {len(articles)} Help Center articles.")


def run():
    with app.app_context():
        db.create_all()

        # --- Super Admin -------------------------------------------------------
        admin_email = app.config["SUPERADMIN_EMAIL"]
        if not User.query.filter_by(email=admin_email).first():
            admin = User(name="Platform Admin", email=admin_email, role=Role.SUPER_ADMIN.value)
            admin.set_password(app.config["SUPERADMIN_PASSWORD"])
            db.session.add(admin)
            db.session.commit()
            print(f"[OK] Super admin created: {admin_email}")
        else:
            print(f"[SKIP] Super admin already exists: {admin_email}")

        # --- Help Center content -------------------------------------------------
        seed_help_articles()

        # --- Demo shop -----------------------------------------------------------
        if Shop.query.filter_by(name="Sharma Auto Spares").first():
            print("[SKIP] Demo shop already exists. Nothing more to seed.")
            return

        shop = Shop(
            name="Sharma Auto Spares", gst_number="27ABCDE1234F1Z5",
            phone="9876543210", address="Shop No. 4, Wardha Road, Nagpur",
            status=ShopStatus.ACTIVE.value,
        )
        db.session.add(shop)
        db.session.flush()

        sub = Subscription(
            shop_id=shop.id, plan_name="Standard", amount=999,
            start_date=date.today(), end_date=date.today() + timedelta(days=365),
            status="active",
        )
        db.session.add(sub)

        owner = User(shop_id=shop.id, name="Ramesh Sharma", email="owner@sharmaauto.com",
                     role=Role.OWNER.value, phone="9876543210")
        owner.set_password("Owner@123")
        db.session.add(owner)

        employee = User(shop_id=shop.id, name="Vikram", email="employee@sharmaauto.com",
                         role=Role.EMPLOYEE.value, phone="9123456780")
        employee.set_password("Employee@123")
        db.session.add(employee)
        db.session.flush()

        supplier = Supplier(shop_id=shop.id, name="Bajaj Auto Distributors",
                             phone="9988776655", gst_number="27SUPPL1234F1Z9")
        db.session.add(supplier)
        db.session.flush()

        main_godown = get_default_godown(shop.id)
        main_godown.name = "Main Godown (Wardha Road)"
        branch_godown = Godown(shop_id=shop.id, name="Ring Road Branch Godown",
                                address="Ring Road, Nagpur")
        db.session.add(branch_godown)
        db.session.flush()

        demo_parts = [
            dict(name="Front Brake Pad Set", oem_number="BP-1023", vehicle_type="bike",
                 vehicle_model="Pulsar 150", brand="Bajaj", category="Brakes",
                 purchase_price=250, selling_price=400, gst_percent=18, hsn_code="8714",
                 minimum_stock=10, rack_location="A1", opening=25),
            dict(name="Engine Oil Filter", oem_number="OF-2201", vehicle_type="car",
                 vehicle_model="Swift", brand="Maruti", category="Engine",
                 purchase_price=120, selling_price=220, gst_percent=18, hsn_code="8421",
                 minimum_stock=15, rack_location="B2", opening=8),
            dict(name="Heavy Duty Clutch Plate", oem_number="CP-3390", vehicle_type="truck",
                 vehicle_model="Tata 1613", brand="Tata OEM", category="Clutch",
                 purchase_price=1800, selling_price=2600, gst_percent=28, hsn_code="8708",
                 minimum_stock=5, rack_location="C1", opening=3),
            dict(name="Hydraulic Pump Seal Kit", oem_number="HP-4410", vehicle_type="jcb",
                 vehicle_model="3DX", brand="JCB Genuine", category="Hydraulics",
                 purchase_price=950, selling_price=1400, gst_percent=18, hsn_code="8413",
                 minimum_stock=6, rack_location="D1", opening=2),
            dict(name="Tractor Front Axle Bush", oem_number="AB-5120", vehicle_type="tractor",
                 vehicle_model="Mahindra 575", brand="Mahindra", category="Suspension",
                 purchase_price=340, selling_price=520, gst_percent=18, hsn_code="8708",
                 minimum_stock=8, rack_location="E1", opening=12),
        ]

        parts_by_name = {}
        for pd in demo_parts:
            opening = pd.pop("opening")
            part = Part(shop_id=shop.id, supplier_id=supplier.id,
                        purchase_price=Decimal(pd["purchase_price"]),
                        selling_price=Decimal(pd["selling_price"]),
                        gst_percent=Decimal(pd["gst_percent"]), **{k: v for k, v in pd.items()
                        if k not in ("purchase_price", "selling_price", "gst_percent")})
            db.session.add(part)
            db.session.flush()

            if part.name == "Front Brake Pad Set":
                # Split across two godowns to demonstrate the stock-transfer feature.
                main_qty = opening - (opening // 3)
                branch_qty = opening // 3
                apply_stock_change(part, main_qty, "adjustment", owner.id,
                                    reference_type="opening_stock", godown_id=main_godown.id)
                apply_stock_change(part, branch_qty, "adjustment", owner.id,
                                    reference_type="opening_stock", godown_id=branch_godown.id)
            else:
                apply_stock_change(part, opening, "adjustment", owner.id, reference_type="opening_stock")
            parts_by_name[part.name] = part

        labour = LabourCharge(shop_id=shop.id, name="Fitting Charge", price=Decimal("150"))
        db.session.add(labour)
        db.session.add(LabourCharge(shop_id=shop.id, name="Service Charge", price=Decimal("300")))

        # A sample customer + invoice so the dashboard isn't empty on first login
        customer = Customer(shop_id=shop.id, name="Anil Kumar", mobile="9090909090",
                             vehicle_number="MH31AB1234", vehicle_type="bike")
        db.session.add(customer)
        db.session.flush()

        part = parts_by_name["Front Brake Pad Set"]
        invoice = Invoice(
            shop_id=shop.id, invoice_number=generate_invoice_number(shop.id),
            customer_id=customer.id, vehicle_number=customer.vehicle_number,
            vehicle_type=customer.vehicle_type, created_by=owner.id,
            payment_method=PaymentMethod.CASH.value, payment_status=PaymentStatus.PAID.value,
        )
        db.session.add(invoice)
        db.session.flush()

        qty = 2
        line_total = qty * part.selling_price
        db.session.add(InvoiceItem(
            invoice_id=invoice.id, part_id=part.id, part_name_snapshot=part.name,
            quantity=qty, unit_price=part.selling_price, gst_percent=part.gst_percent,
            line_total=line_total,
        ))
        apply_stock_change(part, -qty, "sale", owner.id, reference_type="invoice", reference_id=invoice.id)

        gst_amt = line_total * part.gst_percent / (100 + part.gst_percent)
        invoice.subtotal = line_total
        invoice.gst_total = gst_amt
        invoice.grand_total = line_total
        invoice.amount_paid = line_total

        db.session.commit()

        print("[OK] Demo shop 'Sharma Auto Spares' created with sample data.")
        print("     Owner login:    owner@sharmaauto.com / Owner@123")
        print("     Employee login: employee@sharmaauto.com / Employee@123")


if __name__ == "__main__":
    run()

